# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get install git build-essential pkg-config libtool automake autopoint gettext subversion yasm cvs cmake ragel
  displayName: 'Install basics'
- script: cd contrib && $ mkdir native && cd native && ../bootstrap && make && cd ../..
  displayName: 'Compile dev basics'
- script: ./configure --help
  displayName: './configure --help'
- script: make
  displayName: 'make'
  

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
